### ISSUE TITLE
Possible typo in readme might cause a glitch

### ISSUE THREAD

**Issue by guy-roberts** [krisleech/wisper-activerecord#21]
Alright Kris,

Been trying out wisper-activerecord for indexing ElasticSearch when records change. In the readme.md it says (once);

meeting.subscribe(Auditor.new)

Auditor is a Singleton,  should this be 

meeting.subscribe(Auditor.instance)

Wonder if that's why people were getting that message about a class being unloaded from the module tree ?

**Comment by krisleech** [comment]
Hey! You are right it should be `instance` not `new`. Have a biscuit :wink: 

I'll leave this issue open so I remember to fix it.

I think I did `new` for the initial example because some people might not be familiar with `instance`. Maybe I should either change the first example to something else or change `Auditor` to not be a Singelton...

**Comment by guy-roberts** [comment]
I had a Custard Cream, thanks.
